module.exports = {
  'comma-dangle': [2, 'always-multiline'],
  'no-cond-assign': 2,
  'no-console': 1,
  'no-constant-condition': 1,
  'no-control-regex': 2,
  'no-debugger': 1,
  'no-dupe-args': 2,
  'no-dupe-keys': 2,
  'no-duplicate-case': 2,
  'no-empty-character-class': 2,
  'no-empty': 2,
  'no-ex-assign': 2,
  'no-extra-boolean-cast': 2,
  'no-extra-parens': 0,
  'no-extra-semi': 2,
  'no-func-assign': 2,
  'no-inner-declaration': 0,
  'no-irregular-whitespace': 2,
  'no-negated-in-lhs': 2,
  'no-obj-calls': 1,
  'no-sparse-arrays': 2,
  'no-regex-spaces': 2,
  'no-unexpected-multiline': 2,
  'no-unreachable': 2,
  'use-isnan': 2,
  'valid-jsdoc': 0,
  'valid-typeof': 2
};
