module.exports = {
  "arrow-body-style": 2,
  "arrow-parens": 0,
  "arrow-spacing": 2,
  "constructor-super": 2,
  "generator-star-spacing": [2, 'after'],
  "no-class-assign": 2,
  "no-confusing-arrow": 2,
  "no-const-assign": 2,
  "no-dupe-class-members": 2,
  "no-new-symbol": 2,
  "no-this-before-super": 2,
  "no-var": 2,
  "no-useless-constructor": 2,
  "object-shorthand": 2,
  "prefer-const": 2,
  "prefer-reflect": 0,
  "prefer-rest-params": 2,
  "prefer-spread": 2,
  "prefer-template": 2,
  "require-yield": 2,
  "template-curly-spacing": 0,
  "yield-star-spacing": 0
};
