module.exports = {
  'arrow-body-style': 2,
  'arrow-parens': 0,
  'arrow-spacing': 2,
  'constructor-super': 2,
  'generator-star-spacing': 0,
  'no-class-assign': 2,
  'no-confusing-arrow': 0,
  'no-const-assign': 2,
  'no-dupe-class-members': 2,
  'no-new-symbol': 2,
  'no-this-before-super': 2,
  'no-useless-constructor': 0,
  'no-var': 2,
  'object-shorthand': 2,
  'prefer-arrow-callback': 2,
  'prefer-const': 2,
  'prefer-reflect': 0,
  'prefer-rest-params': 2,
  'prefer-spread': 2,
  'prefer-template': 2,
  'require-yield': 2,
  'rest-spread-spacing': ["error", "never"],
  'template-curly-spacing': 0,
  'yield-star-spacing': 0
};
