module.exports = {
  'import/no-unresolved': 0,
  'import/named': 0,
  'import/default': 2,
  'import/namespace': 2,
  'import/no-restricted-paths': 2,
  'import/export': 2,
  'import/no-named-as-default': 2,
  'import/no-named-as-default-member': 2,
  'import/no-deprecated': 2,
  'import/no-extraneous-dependencies': 0,
  'import/no-mutable-exports': 2,
  'import/no-commonjs': 0,
  'import/no-amd': 0,
  'import/no-nodejs-modules': 0,
  'import/imports-first': 2,
  'import/no-duplicates': 2,
  'import/no-namespace': 0,
  'import/extensions': 0,
  'import/order': 0,
  'import/newline-after-import': 1,
  'import/prefer-default-export': 1,
};
