module.exports = {
  'array-bracket-spacing': 2,
  'block-spacing': 2,
  'brace-style': 2,
  'capitalized-comments': 0,
  'comma-spacing': 2,
  'comma-style': 2,
  'computed-property-spacing': 2,
  'consistent-this': 2,
  'eol-last': 2,
  'func-name-matching': 2,
  'func-names': 0,
  'func-style': 0,
  'id-blacklist': 0,
  'id-length': 0,
  'id-match': 0,
  'jsx-quotes': [2, 'prefer-double'],
  'key-spacing': 2,
  'keyword-spacing': 2,
  'linebreak-style': 0,
  'lines-around-comment': 0,
  'max-depth': 0,
  'max-len': 0,
  'max-lines': 0,
  'max-nested-callbacks': 0,
  'max-params': 0,
  'max-statements-per-line': [2, { max: 1 }],
  'max-statements': 0,
  'new-cap': 0,
  'new-parens': 2,
  'newline-after-var': 0,
  'newline-per-chained-call': 0,
  'no-array-constructor': 2,
  'no-bitwise': 2,
  'no-continue': 2,
  'no-duplicate-imports': 0,
  'no-inline-comments': 0,
  'no-lonely-if': 2,
  'no-mixed-spaces-and-tabs': 2,
  'no-multi-assign': 2,
  'no-multiple-empty-lines': 0,
  'no-negated-condition': 2,
  'no-nested-ternary': 2,
  'no-new-object': 2,
  'no-plusplus': [2, { allowForLoopAfterthoughts: true }],
  'no-restricted-syntax': 0,
  'no-spaced-func': 2,
  'no-ternary': 0,
  'no-underscore-dangle': 0,
  'no-unneeded-ternary': 2,
  'no-useless-computed-key': 2,
  'no-useless-escape': 2,
  'no-whitespace-before-property': 2,
  'nonblock-statement-body-position': [2, 'beside'],
  'object-curly-newline': 0,
  'object-curly-spacing': [2, 'always'],
  'object-property-newline': 0,
  'one-var-declaration-per-line': 0,
  'one-var': 0,
  'operator-assignment': 2,
  'operator-linebreak': 0,
  'padded-blocks': 0,
  'quote-props': [2, 'as-needed'],
  'require-jsdoc': 0,
  'semi-spacing': 2,
  'sort-imports': 0,
  'sort-vars': 0,
  'space-before-blocks': 0,
  'space-before-function-paren': [2, 'never'],
  'space-in-parens': 2,
  'space-infix-ops': 2,
  'space-unary-ops': 2,
  'spaced-comment': 0,
  'wrap-regex': 0,
  camelcase: 2,
  indent: 0,
  quotes: [2, 'single'],
  semi: 2,
};
