name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: 'true'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install
        run: |
          yarn
      - name: test
        run: |
          yarn test
