name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: 'true'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18
        uses: actions/setup-node@master
        with:
          node-version: 18
      - name: install
        run: |
          corepack enable
          pnpm i
      - name: test
        run: |
          pnpm test
